site_name: Earth Defense Force - Wiki

theme:
  name: material
  logo: images/edf5_logo_small.png
  favicon: images/edf5_logo_small.png
  features:
    - navigation.indexes
    # - navigation.sections
    # - navigation.tabs
    - navigation.top
    - navigation.tracking
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo

# mermaid support
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - glightbox:
      skip_classes:
          - skip-lightbox
  - git-revision-date-localized

